[csv]

[csv.double]
columns_per_page = 2
rows_per_page = 100
[csv.double.columns]
position = "nr."
artist = "artiest"
title = "titel"

[csv.single]
columns_per_page = 1
rows_per_page = 80
[csv.single.columns]
position = "nr."
artist = "artiest"
title = "titel"
timestamp = "tijd"

[json]

[json.sorted]
relevant = true

[json.sorted.fields]
artiest = "artist"
titel = "title"
album_version = "album_version"
jaar = "year"
timestamp = "timestamp"

[json.sorted.wiki]
artiest = "artist"
titel = "title"
year = "year"
title_link = "title_link"

[json.sorted.columns]
position = "nr."
artist = "artiest"
title = "titel"
year = "jaar"
timestamp = "tijd"
