[csv]

[csv.double]
columns_per_page = 2
rows_per_page = 100
[csv.double.columns]
position = "nr."
artist = "artiest"
title = "titel"

[csv.single]
columns_per_page = 1
rows_per_page = 80
[csv.single.columns]
position = "nr."
artist = "artiest"
title = "titel"
timestamp = "tijd"
