[csv]

[csv.double]
columns_per_page = 2
rows_per_page = 100
[csv.double.columns]
position = "nr."
artist = "artiest"
title = "titel"

[csv.single]
columns_per_page = 1
rows_per_page = 80
[csv.single.columns]
position = "nr."
artist = "artiest"
title = "titel"
timestamp = "tijd"

[json]

[json.sorted]
[json.sorted.fields]
artiest = "artist"
titel = "title"
album_version = "album_version"
yr = "year"
jaar = "year"
timestamp = "timestamp"
